import itertools
from typing import Any, Dict, Optional, Tuple, TYPE_CHECKING
from multiprocessing import get_context
from functools import partial
from tqdm import tqdm
import gurobipy as gp
import numpy as np
import torch
from scipy.spatial.distance import cdist

from forge.processor import MIPProcessor, _MIPUtils
from forge.utils import save_pickle

if TYPE_CHECKING:
    from forge.embeddings import Forge


class GapInfo:
    def __init__(self, lp_obj: float, lp_sol: Any, mip_obj: float, mip_sol: Any, gap_ratio: float):
        self.lp_obj = lp_obj
        self.lp_sol = lp_sol
        self.mip_obj = mip_obj
        self.mip_sol = mip_sol
        self.gap_ratio = gap_ratio


class TripletInfo:
    """Container for triplet training data used to fine-tune variable probability prediction.

    Attributes
    ----------
    triplets : np.ndarray
        Integer array of shape (N, 3) where each row is [anchor, positive, negative] variable index.
    y_true : torch.Tensor
        Binary tensor of shape (num_vars, 1) where 1 = variable appeared in at least one solution.
    """

    def __init__(self, triplets: np.ndarray, y_true: torch.Tensor):
        self.triplets = triplets
        self.y_true = y_true


class HintInfo:
    """Container for warm-start hints generated by the variable probability head.

    Attributes
    ----------
    hint_ones : np.ndarray
        Variable indices to hint as 1.
    hint_zeros : np.ndarray
        Variable indices to hint as 0.
    hint_pri_ones : list[int]
        Priority ranks for the 1-hints (higher = more confident).
    hint_pri_zeros : list[int]
        Priority ranks for the 0-hints (higher = more confident).
    """

    def __init__(self, hint_ones, hint_zeros, hint_pri_ones, hint_pri_zeros):
        self.hint_ones = hint_ones
        self.hint_zeros = hint_zeros
        self.hint_pri_ones = hint_pri_ones
        self.hint_pri_zeros = hint_pri_zeros


class MIPLabeler:

    def __init__(self):
        pass

    @staticmethod
    def convert_mip_to_gapinfo(input_mip_folder,
                               input_mip_instances_file: Optional[str],
                               output_mip_to_gapinfo_pkl,
                               gapinfo_time_limit: int = 120,
                               gurobi_num_threads: int = 1,
                               num_parallel_workers: int = 1,
                               has_return=False) -> Dict[str, GapInfo]:

        # Normalize num_parallel_workers
        if num_parallel_workers is None or num_parallel_workers < 1:
            num_parallel_workers = 1

        mip_files = _MIPUtils.get_only_mip_files(input_mip_folder, input_mip_instances_file, is_sort_by_size=False)

        mip_to_gapinfo: Dict[str, GapInfo] = {}

        # Sequential path when using a single worker
        if num_parallel_workers == 1:
            # Start Gurobi environment and set limits
            gurobi_env = _MIPUtils.start_gurobi_env()
            gurobi_env.setParam("TimeLimit", gapinfo_time_limit)
            gurobi_env.setParam("Threads", gurobi_num_threads)

            for mip_file in tqdm(mip_files):
                mip_to_gapinfo[mip_file] = MIPLabeler._mip_file_to_gapinfo(mip_file, gurobi_env)

            gurobi_env.close()
        else:
            # Parallel path using multiprocessing with the requested number of workers
            ctx = get_context("spawn")
            with ctx.Pool(processes=num_parallel_workers) as pool:
                worker = partial(MIPLabeler._run_gapinfo_worker,
                                 gapinfo_time_limit=gapinfo_time_limit,
                                 gurobi_num_threads=gurobi_num_threads)

                for result in tqdm(pool.imap_unordered(worker, mip_files), total=len(mip_files)):
                    if result:
                        mip_file, gapinfo = result
                        mip_to_gapinfo[mip_file] = gapinfo

        save_pickle(mip_to_gapinfo, output_mip_to_gapinfo_pkl)

        return mip_to_gapinfo if has_return else None


    @staticmethod
    def _mip_file_to_gapinfo(mip_file: str, gurobi_env) -> Optional[GapInfo]:
        """
            On success, returns GapInfo object.
            On fail, returns None.
        """

        # Create mip model
        mip_model: gp.Model = gp.read(mip_file, env=gurobi_env)

        # Solve LP relaxation
        lp_model = mip_model.copy().relax()
        lp_model.optimize()

        # Solve MIP within time limit
        mip_model.optimize()

        # Skip instances that are infeasible or unbounded
        if mip_model.status == gp.GRB.status.INF_OR_UNBD or lp_model.status == gp.GRB.status.INF_OR_UNBD:
            print(f"\rSkipped (INF_OR_UNBD) | MIP status={mip_model.status}, "
                  f"LP status={lp_model.status} | {mip_file}", end="")
            gurobi_env.close()
            return None

        # Skip instances without a solution
        if mip_model.SolCount < 1 or lp_model.SolCount < 1:
            print(f"\rSkipped (No Solution) | MIP status={mip_model.status}, "
                  f"LP status={lp_model.status} | {mip_file}", end="")
            gurobi_env.close()
            return None

        # Retrieve lp and mip objective values and solutions
        lp_obj = lp_model.objVal
        lp_sol = [v.x for v in lp_model.getVars()]
        mip_obj = mip_model.objVal
        mip_sol = [v.x for v in mip_model.getVars()]

        # Calculate ratio (handle zero division)
        # For minimization, LP ≤ MIP, so ratio = lp_obj / mip_obj.
        # For maximization, LP ≥ MIP, so ratio = mip_obj / lp_obj.
        if mip_model.ModelSense == gp.GRB.MINIMIZE:
            ratio = 1.0 if mip_obj == 0 else lp_obj / mip_obj
        else:  # maximization
            ratio = 1.0 if lp_obj == 0 else mip_obj / lp_obj

        print("\rRatio:", ratio, "|", mip_file)
        return GapInfo(lp_obj=lp_obj, lp_sol=lp_sol, mip_obj=mip_obj, mip_sol=mip_sol, gap_ratio=ratio)

    @staticmethod
    def _run_gapinfo_worker(mip_file: str,
                            gapinfo_time_limit: int,
                            gurobi_num_threads: int) -> Optional[Tuple[str, GapInfo]]:

        """Worker function to compute GapInfo for a single MIP instance.

        This function is designed to be picklable so it can be used with multiprocessing.
        It creates and tears down its own Gurobi environment inside each worker process.

        On success, returns GapInfo object.
        On fail, returns None.
        """

        try:
            # Start Gurobi environment and set limits for this worker
            gurobi_env = _MIPUtils.start_gurobi_env()
            gurobi_env.setParam("TimeLimit", gapinfo_time_limit)
            gurobi_env.setParam("Threads", gurobi_num_threads)

            # Create gapinfo
            gapinfo = MIPLabeler._mip_file_to_gapinfo(mip_file, gurobi_env)

            gurobi_env.close()

            # Return mip_file also so that we know which gapinfo is returned
            return mip_file, gapinfo

        except Exception as exc:
            print(f"\nError while processing {mip_file}: {exc}")
            try:
                # Best-effort cleanup; in some failure modes env may not exist
                gurobi_env.close()
            except Exception:
                pass
            return None

    @staticmethod
    def convert_mip_to_tripletinfo(input_mip_folder,
                                   input_mip_instances_file,
                                   output_mip_to_tripletinfo_pkl,
                                   forge_model: "Forge",
                                   triplet_time_limit: int = 300,
                                   triplet_num_solutions: int = 5,
                                   has_return=False) -> Dict[str, TripletInfo]:
        """Generate triplet training data from MIP files using a pretrained Forge model.

        For each MIP instance, solves with a solution pool, groups variables by
        solution count, and creates triplets (anchor, positive, negative) for
        triplet margin loss training. Variables appearing in the same number of
        solutions form anchor-positive pairs; the closest never-picked variables
        serve as negatives.

        Parameters
        ----------
        input_mip_folder : str
            Path to directory containing MIP files.
        input_mip_instances_file : Optional[str]
            Path to a text file listing instance names to include.
        output_mip_to_tripletinfo_pkl : str
            Path to save the resulting TripletInfo dictionary as a pickle file.
        forge_model : Forge
            Pretrained Forge model used to generate variable embeddings.
        triplet_time_limit : int, default=300
            Time limit in seconds for each solution-pool MIP solve.
        triplet_num_solutions : int, default=5
            Number of solutions to collect via Gurobi's solution pool.
        has_return : bool, default=False
            If True, return the generated dictionary.

        Returns
        -------
        Dict[str, TripletInfo] or None
            Mapping from MIP file path to TripletInfo, or None if has_return is False.
        """

        mip_files = _MIPUtils.get_only_mip_files(input_mip_folder, input_mip_instances_file, is_sort_by_size=False)

        mip_to_tripletinfo: Dict[str, TripletInfo] = {}

        gurobi_env = _MIPUtils.start_gurobi_env()

        for mip_file in tqdm(mip_files):
            result = MIPLabeler._mip_file_to_tripletinfo(
                mip_file, forge_model, gurobi_env, triplet_time_limit, triplet_num_solutions
            )
            if result is not None:
                mip_to_tripletinfo[mip_file] = result

        gurobi_env.close()

        save_pickle(mip_to_tripletinfo, output_mip_to_tripletinfo_pkl)

        return mip_to_tripletinfo if has_return else None

    @staticmethod
    def _mip_file_to_tripletinfo(mip_file: str,
                                 forge_model: "Forge",
                                 gurobi_env,
                                 triplet_time_limit: int = 300,
                                 triplet_num_solutions: int = 5) -> Optional[TripletInfo]:
        """Generate TripletInfo for a single MIP file.

        On success, returns TripletInfo object.
        On fail or skip, returns None.
        """

        try:
            # Read MIP file
            mip_model = gp.read(mip_file, env=gurobi_env)

            # Convert to MIPInfo
            mipinfo = MIPProcessor._mip_model_to_mipinfo(mip_model)

            # Forward pass through pretrained Forge to get variable embeddings
            original_mode = forge_model.is_eval_mode
            forge_model.is_eval_mode = True
            forge_model.eval()

            with torch.no_grad():
                h_list, _, _, _, _ = forge_model.forward(
                    mipinfo.feature_tensor.to(forge_model.device),
                    mipinfo.num_cons, mipinfo.num_vars,
                    mipinfo.edge_index.to(forge_model.device),
                    mipinfo.edge_weight.to(forge_model.device)
                )

            forge_model.is_eval_mode = original_mode

            num_cons = mipinfo.num_cons
            num_vars = mipinfo.num_vars

            # Continuous and quantized variable embeddings
            emb = h_list[0][num_cons:].detach().cpu().numpy()
            quantized_emb = h_list[1][num_cons:].detach().cpu().numpy()

            # Solve MIP with solution pool
            gurobi_env.setParam("TimeLimit", triplet_time_limit)
            mip_model.Params.PoolSearchMode = 1
            mip_model.Params.PoolSolutions = triplet_num_solutions
            mip_model.optimize()

            if mip_model.SolCount < 1:
                print(f"\rSkipped (No Solution) | {mip_file}", end="")
                return None

            # Count how many solutions each variable appears in
            var_sol_count = {i: 0 for i in range(num_vars)}
            for sol_idx in range(mip_model.SolCount):
                mip_model.Params.SolutionNumber = sol_idx
                xn = np.array(mip_model.Xn)
                for v in np.where(xn > 0)[0]:
                    var_sol_count[v] += 1

            # Group variables by solution count
            vars_by_count = {i: [] for i in range(mip_model.SolCount + 1)}
            for v, count in var_sol_count.items():
                vars_by_count[count].append(v)

            # Anchor-positive pairs: variables appearing in the same number of solutions
            train_set = []
            for s in range(1, mip_model.SolCount + 1):
                if len(vars_by_count[s]) >= 2:
                    train_set += list(itertools.combinations(vars_by_count[s], 2))

            if len(train_set) == 0:
                return None

            positives = list(set(range(num_vars)) - set(vars_by_count[0]))

            # Pairwise distance matrices
            dist_emb = cdist(emb, emb, metric='euclidean')
            dist_quant = cdist(quantized_emb, quantized_emb, metric='euclidean')

            # Exclude positive-positive and self pairs from being selected as negatives
            for i in positives:
                dist_emb[i, i] = np.inf
                dist_quant[i, i] = np.inf
            for i in positives:
                for j in positives:
                    if i != j:
                        dist_emb[i, j] = np.inf
                        dist_quant[i, j] = np.inf

            # Top-3 closest negatives for each variable (in each distance space)
            closest_negatives = np.argpartition(dist_emb, kth=2, axis=1)[:, :3]
            closest_negatives_quant = np.argpartition(dist_quant, kth=2, axis=1)[:, :3]

            # Build triplets: 9 triplets per anchor-positive pair
            triplets = []
            for anchor, pos in train_set:
                triplets.append([anchor, pos, closest_negatives[anchor, 0]])
                triplets.append([anchor, pos, closest_negatives[anchor, 1]])
                triplets.append([anchor, pos, closest_negatives[anchor, 2]])
                triplets.append([pos, anchor, closest_negatives[pos, 0]])
                triplets.append([pos, anchor, closest_negatives[pos, 1]])
                triplets.append([pos, anchor, closest_negatives[pos, 2]])
                triplets.append([anchor, pos, closest_negatives_quant[anchor, 0]])
                triplets.append([anchor, pos, closest_negatives_quant[anchor, 1]])
                triplets.append([anchor, pos, closest_negatives_quant[anchor, 2]])

            triplets = np.array(triplets)

            y_true = torch.zeros(num_vars, 1)
            y_true[positives] = 1

            print(f"\rTriplets: {len(triplets)} | {mip_file}")
            return TripletInfo(triplets=triplets, y_true=y_true)

        except Exception as exc:
            print(f"\nError while processing {mip_file}: {exc}")
            return None