from typing import List, Any, Dict, Optional
import numpy as np
import os
from tqdm import tqdm
import pickle as pkl

import gurobipy as gp

import time
import scipy.sparse as sp
import yaml
from forge.utils import Num, check_true, Constants, _overwrite_if_given, save_pickle


class MIPInfo:
    def __init__(self,
                 instance_name: str = None,
                 dgl: Any = None,
                 feature_matrix=None,
                 num_constraints: int = None,
                 num_variables: int = None):
        self.instance_name = instance_name
        self.dgl = dgl
        self.feature_matrix = feature_matrix  # TODO: what's the row,column?
        self.num_constraints = num_constraints
        self.num_variables = num_variables


class MIPProcessor:
    """
    MIP Data processor
    """

    def __init__(self,
                 train_config_file_path: Optional[str] = Constants.default_train_config_file,
                 train_config_version: Optional[str] = Constants.default_config_version,
                 seed: Optional[int] = None):
        super().__init__()

        # Read all configs from the given file
        with open(train_config_file_path, 'r') as f:
            all_configs = yaml.safe_load(f)

        # Set the selected config
        config = all_configs.get(train_config_version, {})

        self.seed = _overwrite_if_given(config.get('seed'), seed)

    def convert_mip_to_mipinfo(self, input_folder, output_file, perturb_list=None, has_return=False) \
            -> Optional[Dict[str, List[Any]]]:
        """
            input_folder : path of directory with MPS / LP files
            output_file : path and file name to save processed list of instances
            perturb : list of perturbation ratios between 0-1 to create new instances by randomly dropping constraints
            has_return : If true, returns the mip_to_dgl dictionary else only writes to file

            Returns: Dictionary mapping MIP file paths to [DGL graph, feature matrix, num_constraints, num_variables]
        """

        if perturb_list is None:
            perturb_list = []

        all_files = os.listdir(input_folder)
        files_and_sizes = [os.path.join(input_folder, path) for path in all_files]
        files_and_sizes = [x for x in files_and_sizes if 'mps' in x or 'lp' in x]
        sorted_instances = sorted(files_and_sizes, key=os.path.getsize)

        # Setup Gurobi environment
        try:
            from gurobi_onboarder import init_gurobi
            gurobi_venv, GUROBI_FOUND = init_gurobi.initialize_gurobi()
        except:
            gurobi_venv = gp.Env(empty=True)
        gurobi_venv.setParam("OutputFlag", 0)
        gurobi_venv.start()

        mip_to_mipinfo = {}
        for idx in tqdm(range(len(sorted_instances))):

            # Read MPS file
            mip_model = gp.read(sorted_instances[idx], env=gurobi_venv)

            # Generate MIPInfo object
            mip_info = self.generate_mip_info(mip_model)
            mip_info.instance_name = sorted_instances[idx]
            mip_to_mipinfo[mip_info.instance_name] = mip_info

            if perturb_list:
                for ratio in perturb_list:
                    mip_model = gp.read(sorted_instances[idx], env=gurobi_venv)

                    # Randomly remove a given ratio of constraints to create a new MIP instance
                    # TODO this needs to have a seed for reproducibility. See the default self.seed
                    # TODO should we be saving these perturbed instances to disk? Add a flag to enable save?
                    cons = mip_model.getConstrs()
                    cons_remove_ = np.random.choice(cons, int(len(cons) * ratio), replace=False)
                    for c in cons_remove_:
                        mip_model.remove(c)
                    mip_model.update()

                    # Generate MIPInfo object
                    mip_info = self.generate_mip_info(mip_model)
                    mip_info.instance_name = sorted_instances[idx] + '_perturbed_' + str(ratio)
                    mip_to_mipinfo[mip_info.instance_name] = mip_info

                    # TODO: I think you can add constraints back and update the model instead of re-reading it
                    # TODO: this way, you can remove gp.read() in the for ratio loop

        save_pickle(mip_to_mipinfo, output_file)

        return mip_to_mipinfo if has_return else None

    @staticmethod
    def get_train_list(self, path_list) -> List[List[Any]]:
        """
        path_list : List of paths of mip_to_dgl dictionaries generated by calling get_instance_dict()
        """
        train_list = []
        for p in path_list:
            with open(p, 'rb') as file:
                mip_to_dgl = pkl.load(file)
            for inst_name in mip_to_dgl:
                train_list.append(mip_to_dgl[inst_name])

        return train_list

    @staticmethod
    def get_dgl_graph(adj, feats, coeff_adj):
        """
        Called by generate_mip_graph()
        Returns a DGL object
        """

        coeff_adj_coo = coeff_adj.tocoo()
        edge_weights = coeff_adj[coeff_adj_coo.row, coeff_adj_coo.col].flatten()
        edge_weights = (edge_weights - edge_weights.min()) / (edge_weights.max() - edge_weights.min() + 1e-6)
        edge_weights += 1e-4

        features = torch.FloatTensor(np.array(feats))
        # adj = normalize_adj(adj)

        if not adj:
            return False

        adj_sp = adj.tocoo()
        g = dgl.graph((adj_sp.row, adj_sp.col))
        g.ndata["feat"] = features
        g.edata["weight"] = torch.FloatTensor(edge_weights).T

        check_true(g.num_nodes() == g.ndata["feat"].shape[0],
                   ValueError(f"Error: graph has {g.num_nodes()} nodes but "
                              f"feature matrix has {g.ndata['feat'].shape[0]} rows"))
        return g

    @staticmethod
    def generate_mip_info(mip_model, is_debug=False):

        # TODO: this block needs some commentary explaining what is being done at a high level
        to_remove = [v for v in mip_model.getVars() if not mip_model.getCol(v).size()]
        mip_model.remove(to_remove)
        mip_model.update()

        # Get constraint matrix
        coefficient_matrix = mip_model.getA().todense()
        A = (coefficient_matrix != 0).astype(int)

        # Get objective equation
        # obj = np.array([x.Obj for x in mip_model.getVars()])

        # Create feature vectors for each variable
        variables = mip_model.getVars()
        var_feature_vector = []
        for v in variables:
            feat = [v.VType == gp.GRB.CONTINUOUS,
                    v.VType == gp.GRB.BINARY,
                    v.VType == gp.GRB.INTEGER,
                    v.Obj,
                    v.LB > -gp.GRB.INFINITY,
                    v.UB <= gp.GRB.INFINITY]
            feat = [float(x) for x in feat]
            var_feature_vector.append(feat)

        # Create feature vectors for each constraint
        constraints = mip_model.getConstrs()
        operators = mip_model.Sense
        constraints_feature_vector = []
        for c, o in list(zip(constraints, operators)):
            feat = [o == '=',
                    o == '<',
                    o == '>',
                    c.RHS]
            feat = [float(x) for x in feat]
            constraints_feature_vector.append(feat)

        num_cons = len(constraints)
        num_vars = len(variables)

        s = 0
        if is_debug:
            print("Creating Adjacency")
            s = time.time()

        # Create graph
        adj = np.block([[np.zeros((num_cons, num_cons)), A],
                        [A.T, np.zeros((num_vars, num_vars))]])
        coeff_adj = np.block([[np.zeros((num_cons, num_cons)), coefficient_matrix],
                              [coefficient_matrix.T, np.zeros((num_vars, num_vars))]])
        if is_debug:
            print("Graph Created in ", time.time() - s, "seconds")

        if is_debug:
            print("Computing Feature Vectors")
            s = time.time()

        # Create feature matrix
        constraints_feature_vector = np.array(constraints_feature_vector)
        var_feature_vector = np.array(var_feature_vector)

        # Pad with zeros for equal shapes
        constraints_feature_matrix = np.hstack([constraints_feature_vector,
                                                np.zeros((num_cons, var_feature_vector.shape[1]))])

        var_feature_matrix = np.hstack([np.zeros((num_vars, constraints_feature_vector.shape[1])),
                                        var_feature_vector])

        # Stack up into one feature matrix
        features = np.vstack([constraints_feature_matrix, var_feature_matrix])

        # Column normalize
        features = (features - np.min(features, axis=0)) / (np.max(features, axis=0) - np.min(features, axis=0) + 1e-9)
        features[np.isnan(features)] = 0
        if is_debug:
            print("Feature Vectors Computed in ", time.time() - s, "seconds")

        # Create DGL graph
        if is_debug:
            print("Creating DGL Graph")
            s = time.time()

        dgl = MIPProcessor.get_dgl_graph(sp.csr_matrix(adj), features, sp.csr_matrix(coeff_adj))

        if dgl is False:
            if is_debug:
                print("WARNING: DGL returned false, MIPInfo is empty")
            return MIPInfo()

        # TODO: what's rows/columns of feature matrix? comment here
        feature_matrix = dgl.ndata["feat"]

        if is_debug:
            print("DGL Graph Created in ", time.time() - s, "seconds")

        return MIPInfo(dgl=dgl, feature_matrix=feature_matrix, num_constraints=num_cons, num_variables=num_vars)
