# General
seed: 1283

# Model Architecture Parameters
input_dim: 10
hidden_dim: 1024
codeword_dim: 256
codebook_size: 256
dropout_ratio: 0.4
norm_type: "none"
graph_sage_aggregation: "max" # add/mean/max # was mean before

# Loss Weight Parameters (currently not used) showing values for record keeping
lambda_edge: 100.0
lambda_node: 5.0

# Model Configuration Flags
orthogonal_reg_weight: 5.0
is_eval_mode: false

# Decoder Parameters
decoder_edge_dim: 32

# Vector Quantization Parameters
vq_decay: 0.9
vq_commitment_weight: 1.0
vq_is_cosine_sim: false
vq_stochastic_sample_codes: true
vq_sample_codebook_temp: 0.5
# Training Parameters
epochs: 10
steps_per_instance: 1
learning_rate: 5e-5
weight_decay: 1e-6
max_graph_nodes: 100000
adj_block_size: 5120

# Integral Gap
integral_gap_safety_eps: 0.05