# General
seed: 1283

# Model Architecture Parameters
input_dim: 10
hidden_dim: 1024
codeword_dim: 1024
codebook_size: 5000
dropout_ratio: 0.4
norm_type: "none"
graph_sage_aggregation: "mean" # add/mean/max

# Loss Weight Parameters (currently not used)
lambda_edge: 1
lambda_node: 1

# Model Configuration Flags
orthogonal_reg_weight: 0.0
is_eval_mode: false

# Decoder Parameters
decoder_edge_dim: 32

# Vector Quantization Parameters
vq_decay: 0.8
vq_commitment_weight: 0.25
vq_is_cosine_sim: true

# Training Parameters
epochs: 10
steps_per_instance: 10
learning_rate: 1e-4
weight_decay: 1e-4
max_graph_nodes: 21000
safety_eps: 0.05
adj_block_size: 5120